Add a `tower.yml` file to enable Reports in Nextflow Tower
nf-core/methylseq pull request #281
Opened 2022-12-02 12:59 UTC by ewels

Untested in Tower so far.

2022-12-02 13:00 UTC, FelixKrueger approved these changes
Will test straight away

2022-12-02 17:00 UTC, FelixKrueger requested changes

2022-12-02 17:00 UTC, FelixKrueger commented on tower.yml
> +  "**/fastqc/*_fastq.html":
Maybe try to change this to

```
"**/fastqc/*_fastqc.html":
```

2022-12-02 19:45 UTC, ewels commented on tower.yml
> +  "**/qualimap/*/qualimapReport.html":
```suggestion
  qualimapReport.html:
```

2022-12-02 19:45 UTC, ewels commented on tower.yml
> +  "**/fastqc/*_fastqc.html":
```suggestion
  "*_fastqc.html":
```

2022-12-02 19:46 UTC, ewels commented on tower.yml
> +  "**/bismark/reports/*/*report.html":
```suggestion
  "bismark/reports/*/*report.html":
```

2022-12-02 22:32 UTC, ewels reviewed
Titles are a bit verbose in Tower..

2022-12-02 22:32 UTC, ewels commented on tower.yml
> +    display: "MultiQC HTML report"
```suggestion
    display: "MultiQC report"
```

2022-12-02 22:32 UTC, ewels commented on tower.yml
> +    display: "All samples Bismark reports"
```suggestion
    display: "Bismark sample report"
```

2022-12-02 22:32 UTC, ewels commented on tower.yml
> +    display: "All samples Qualimap reports"
```suggestion
    display: "Qualimap sample report"
```

2022-12-02 22:32 UTC, ewels commented on tower.yml
> +    display: "All samples FastQC reports, before and after trimming"
```suggestion
    display: "FastQC reports"
```

2022-12-02 22:34 UTC, ewels commented on tower.yml
> +    display: "FastQC reports"
```suggestion
  "*_fastqc.html":
    display: "FastQC report, before trimming"
  "*_val_*_fastqc.html":
    display: "FastQC report, after trimming"
```

2022-12-05 08:20 UTC, ewels commented on tower.yml
> +    display: "FastQC report, after trimming"
```suggestion
reports:
  multiqc_report.html:
    display: "MultiQC report"
  bismark_summary_report.html:
    display: "Bismark summary report"
  "bismark/reports/*report.html":
    display: "Bismark sample report"
  "*_val_*_fastqc.html":
    display: "FastQC report, after trimming"
  "*_fastqc.html":
    display: "FastQC report, before trimming"
```

2022-12-09 23:25 UTC, ewels commented
Just failing linting because of the new tools release. Will sort that out with the template merge PR.

2022-12-09 23:25 UTC, merged