Dev -> Master 2.4.0
nf-core/methylseq pull request #321
Opened 2023-06-02 18:56 UTC by sateeshperi

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/methylseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/methylseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-06-05 07:30 UTC, SPPearce requested changes
I don't think that `ignore` is a suitable name for a parameter, I think it should be `ignore_r1`. Similarly with `ignore_3prime` to make it match up.
Generally ok other than that, a few minor points. There are some #TODO strings, I don't know if that is because they are in the template or where they have come from.

2023-06-05 07:30 UTC, SPPearce commented on nextflow_schema.json
> +                "ignore_3prime": {
And this be `ignore_3prime_r1`?

2023-06-05 07:30 UTC, SPPearce commented on nextflow_schema.json
> +                    "help_text": "Ignore the first <int> bp from the 5' end of Read 2 of paired-end sequencing results only. Since the first couple of bases in Read 2 of BS-Seq experiments show a sev
This text needs updating.

2023-06-05 07:30 UTC, SPPearce commented on nextflow.config
> +    ignore                     = 0
I don't like calling this parameter `ignore`, that seems far too generic a name.

2023-06-05 11:50 UTC, sateeshperi commented on nextflow_schema.json
> +                "ignore_3prime": {
good catch. thanks

2023-06-10 05:30 UTC, SPPearce approved these changes
Can you check the genome question, otherwise should be good to go.

2023-06-10 05:30 UTC, SPPearce commented on README.md
> +sample,fastq_1,fastq_2,genome
Does the pipeline actually use the genome column currently? If not, remove from here.

2023-06-12 17:11 UTC, sateeshperi commented on nextflow_schema.json
> +                    "help_text": "Ignore the last 2 bp from the 3' end of Read 1 (or single-end alignment files) when processing the methylation call string. This can remove unwanted biases from the
ah you are right...fixing now

2023-06-12 18:25 UTC, merged