fix annoying PRESEQ failure
nf-core/methylseq pull request #382
Opened 2024-02-22 09:08 UTC by bounlu

Fixes https://github.com/nf-core/methylseq/issues/161

2024-02-28 19:07 UTC, ewels requested changes
Please submit this upstream, to the nf-core modules repo. Direct link to the equivalent file is [here](https://github.com/nf-core/modules/blob/master/modules/nf-core/preseq/lcextrap/main.nf). Once it's merged there we can update the module in this pipeline.

This preseq lcextrap module is used by at least 6 different pipelines (see https://nf-co.re/modules/preseq_lcextrap), so fixing it upstream improves all of them:

> **included in:**
> [atacseq](https://nf-co.re/atacseq/2.1.2/), [chipseq](https://nf-co.re/chipseq/2.0.0/), [cutandrun](https://nf-co.re/cutandrun/3.2.2/), [methylseq](https://nf-co.re/methylseq/2.6.0/), [nascent](https://nf-co.re/nascent/2.1.1/), [rnaseq](https://nf-co.re/rnaseq/3.14.0/)

Thanks,

Phil

2024-03-08 10:39 UTC, ewels commented
@bounlu please shout if you don't intend to submit this upstream, so that someone else can take the task. It'd be nice to get this improvement into the pipeline.

2024-03-08 10:46 UTC, bounlu commented
It would be great if someone else do it. Thanks.

2024-03-11 09:18 UTC, maxulysse commented
https://github.com/nf-core/modules/pull/5091

2024-03-11 11:43 UTC, maxulysse commented
@bounlu the module has been updated upstream.
Now you just need to run `nf-core modules update preseq/lcextrap` on your PR and push the changes

2024-03-22 09:12 UTC, ewels commented
PR in https://github.com/nf-core/methylseq/pull/390

2024-03-22 09:12 UTC, closed without merging